carts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url('^$', views.cart),
    url('^add(\d+)_(\d+)/$', views.add),
    url('^count_judge/$', views.count_judge),
    url('^edit(\d+)_(\d+)/$', views.edit),
    url('^delete(\d+)/$', views.delete),
]

ttshengxian/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('user_part.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^', include('products.urls')),
    url(r'^cart/', include('carts.urls')),
    url(r'^order/', include('order.urls')),
    url(r'^search/', include('haystack.urls')),
]

order/models.py
from django.db import models


class OrderInfo(models.Model):
    order_id = models.CharField(max_length=20, primary_key=True)
    order_user = models.ForeignKey('user_part.UserInfo', on_delete=models.CASCADE)
    order_date = models.DateTimeField(auto_now=True)
    is_Pay = models.BooleanField(default=False)
    total_price = models.DecimalField(max_digits=8, decimal_places=2)
    address = models.CharField(max_length=140)


class OrderDetailInfo(models.Model):
    products = models.ForeignKey('products.ProductInfo', on_delete=models.CASCADE)
    order = models.ForeignKey(OrderInfo, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    count = models.IntegerField()

templates/user/forget.html
{% extends 'foot.html' %}

{% block script %}
<script>
	$(function(){

	var error_username;

	$('.name_input').blur(function() {
		check_user_name();
	});

	function check_user_name(){
        $.get('/user/login_judge/?user_name='+$('.name_input').val(), function (data) {
            if(data.count==0)
            {
                $('.user_error').text('用户名不存在，请重新输入').show();
                error_username = true;
            }
            else
            {
            	$('.user_error').hide();
            	error_username = false;
            }
        });
	}

	$('form').submit(function() {
		check_user_name();

		if (error_username)
		{
			return false;
		}

	});

	})
</script>
{% endblock script %}

{% block main %}
	<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>重置密码</h1>
					<a href="/user/login/">立即登录</a>
				</div>
				<div class="form_input">
					<form action="/user/forget/" method="post">
						{% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="submit" value="提交" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock main %}

templates/user/login.html
{% extends 'foot.html' %}

{% block script %}
<script>
	$(function(){
	var error_username;

	$('.name_input').blur(function() {
		check_user_name();
	});

	function check_user_name(){
        $.get('/user/login_judge/?user_name='+$('.name_input').val(), function (data) {
            if(data.count==0)
            {
                $('.user_error').text('用户名不存在，请前往注册').show();
                error_username = true;
            }
            else
            {
            	$('.user_error').hide();
            	error_username = false;
            }
        });
	}

	if ({{error_pwd}}==1){
		$('.pwd_error').text('密码错误').show()
	}

	$('form').submit(function() {
		check_user_name();

		if (error_username)
		{
			return false;
		}

	});

	})
</script>
{% endblock script %}

{% block main %}
	<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/user/register/">立即注册</a>
				</div>
				<div class="form_input">
					<form action="/user/login_handler/" method="post">
						{% csrf_token %}
						<input type="text" name="username" class="name_input" value="{{ username }}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" value="{{ userpwd }}" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="remember" value="1" checked="checked">
							<label>记住用户名</label>
							<a href="/user/forget/">忘记密码</a>
						</div>
						<input type="submit" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock main %}

templates/user/register.html
{% extends 'foot.html' %}

{% block script %}
	<script type="text/javascript" src="/static/js/register.js"></script>
{% endblock script %}

{% block main %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/logo02.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="/user/login/">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form action="/user/register_handler/" method="post">
					{% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>
{% endblock main %}

templates/user/reset.html
{% extends 'foot.html' %}

{% block script %}
<script>
	$(function(){

	var error_pwd;
	var error_check_password;

	$('#pwd').blur(function() {
		check_pwd();
	});

	$('#cpwd').blur(function() {
		check_cpwd();
	});

	function check_pwd(){
		var len = $('#pwd').val().length;
		if(len<8||len>20)
		{
			$('#pwd').next().html('密码最少8位，最长20位')
			$('#pwd').next().show();
			error_pwd = true;
		}
		else
		{
			$('#pwd').next().hide();
			error_pwd = false;
		}
	}

	function check_cpwd(){
		var pass = $('#pwd').val();
		var cpass = $('#cpwd').val();

		if(pass!=cpass)
		{
			$('#cpwd').next().html('两次输入的密码不一致')
			$('#cpwd').next().show();
			error_check_password = true;
		}
		else
		{
			$('#cpwd').next().hide();
			error_check_password = false;
		}

	}

	$('form').submit(function() {
		check_pwd();
		check_cpwd();

		if (error_pwd || error_check_password)
		{
			return false;
		}

	});

	})
</script>
{% endblock script %}

{% block main %}
	<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>重置密码</h1>
					<a href="/user/login/">立即登录</a>
				</div>
				<div class="form_input">
					<form action="/user/reset/" method="post">
						{% csrf_token %}
						<ul>
							<li>
								<input type="password" name="pwd" id="pwd" placeholder="请输入密码">
								<div class="pwd_error">输入错误</div>
							</li>
							<li>
								<input type="password" name="cpwd" id="cpwd" placeholder="请输入密码">
								<div class="cpwd_error">输入错误</div>
							</li>
							<li>
								<input type="submit" value="重置密码" class="input_submit">
							</li>
						</ul>
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock main %}

templates/user/user_center_info.html
{% extends 'base.html' %}

{% block body %}
	<div class="search_bar clearfix">
		<a href="/" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/" class="active">· 个人信息</a></li>
				<li><a href="/user/order/">· 全部订单</a></li>
				<li><a href="/user/site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
			<div class="info_con clearfix">
			<h3 class="common_title2">基本信息</h3>
					<ul class="user_info_list">
						<li><span>用户名：</span>{{ user_name }}</li>
						<li><span>邮箱：</span>{{ user_email }}</li>
					</ul>
			</div>

			{% if view_list %}
			<h3 class="common_title2">最近浏览</h3>
			<div class="has_view_list">
				<ul class="goods_type_list clearfix">
					{% for each in view_list %}
					<li>
						<a href="/{{ each.id }}/"><img src="/static/{{ each.product_img }}"></a>
						<h4><a href="/{{ each.id }}/">{{ each.product_name }}</a></h4>
						<div class="operate">
							<span class="prize">￥{{ each.product_price }}</span>
							<span class="unit">{{ each.product_unit }}</span>
							<a href="#" class="add_goods" title="加入购物车"></a>
						</div>
					</li>
					{% endfor %}
				</ul>
			</div>
			{% endif %}
		</div>
	</div>
{% endblock body %}

templates/user/user_center_order.html
{% extends 'base.html' %}

{% block body %}
	<div class="search_bar clearfix">
		<a href="/" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/">· 个人信息</a></li>
				<li><a href="/user/order/" class="active">· 全部订单</a></li>
				<li><a href="/user/site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
				{% for each in orders %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ each.order_date }}</li>
					<li class="col02">订单号：{{ each.order_id }}</li>
					{% if each.is_Pay %}
					<li class="col02 stress">已支付</li>
					{% else %}
					<li class="col02 stress">未支付</li>
					{% endif %}
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
								{% for each1 in each.orderdetailinfo_set.all %}
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="/static/{{ each1.products.product_img }}"></li>
									<li class="col02">{{ each1.products.product_name }}<em>{{ each1.price }}/{{ each1.products.product_unit }}</em></li>
									<li class="col03">{{ each1.count }}</li>
									<li class="col04">{{ each1.price }}</li>
								</ul>
								{% endfor %}
							</td>
							<td width="15%">{{ each.total_price }}</td>
							{% if each.is_Pay %}
							<td width="15%">已付款</td>
							<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
							{% else %}
							<td width="15%">待付款</td>
							<td width="15%"><a href="/order/pay/{{ each.order_id }}" class="oper_btn">去付款</a></td>
							{% endif %}
						</tr>
					</tbody>
				</table>
				{% endfor %}

				<div class="pagenation">
					{% if page.has_previous %}
					<a href="/user/order/{{ page.previous_page_number }}"><上一页</a>
					{% endif %}

					{% for each in paginator.page_range %}
					{% if each == page.number %}
					<a href="#" class="active">{{ each }}</a>
					{% else %}
					<a href="/user/order/{{ each }}">{{ each }}</a>
					{% endif %}
					{% endfor %}

					{% if page.has_next %}
					<a href="/user/order/{{ page.next_page_number }}">下一页></a>
					{% endif %}
				</div>
		</div>
	</div>
{% endblock body %}

templates/user/user_center_site.html
{% extends 'base.html' %}

{% block body %}
	<div class="search_bar clearfix">
		<a href="/" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/">· 个人信息</a></li>
				<li><a href="/user/order/">· 全部订单</a></li>
				<li><a href="/user/site/" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>{{ user.user_address }} （{{ user.user_rman }} 收） {{ user.user_pnumber }}</dd>
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="/user/site/" method="POST">
						{% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="r_man">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="address"></textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="mnumber">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="pnumber">
						</div>

						<input type="submit" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>
{% endblock body %}